# Gunakan image Go versi terbaru
FROM golang:1.23.3-alpine

# Set direktori kerja di dalam container
WORKDIR /app

# Copy go.mod dan go.sum, lalu instal dependensi
COPY go.mod go.sum ./
RUN go mod download

# Copy semua file ke dalam container
COPY . .

# Build aplikasi
RUN go build -o main .

# Expose port aplikasi
EXPOSE 8080
# Jalankan aplikasi
CMD ["./main"]
