version: '3.8'

services:
  cv-review-service:
    build: .
    container_name: flawlesscv-python
    env_file:
      - .env
    ports:
      - "5000:5000"
    environment:
      - FLASK_RUN_PORT=5000
      - FLASK_APP=runserver.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - groq_key=your_groq_api_key_here
      - promt=Anda adalah seorang pereview resume dibawah ini adalah sebuah resume, tolong Evaluasi resume ini secara keseluruhan. Berikan masukan mengenai struktur, pemilihan kata, penekanan pada keterampilan yang relevan, dan kesesuaian dengan posisi yang dilamar. Apakah ada informasi yang perlu ditambahkan, dihapus, atau diubah? dan tolong gunakan bahasa indonesia untuk menjelaskannya
      - JWT_KEY=secret
    volumes:
      - .:/app
    networks:
      - flawlesscv-network
    restart: unless-stopped

networks:
  flawlesscv-network:
    driver: bridge
